version: '3.8'

services:
  redis:
    image: redis:7.2.5
    # ports:
    #   - "6379:6379"
    networks:
      - deda-network
  
  deda-backend:
    image: deda-backend:latest
    ports:
      - "3000:3000"
    networks:
      - deda-network

networks:
  deda-network:
    name: deda-network
    external: true
